package com.gwac.model;
// Generated 2016-6-11 16:23:31 by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CatfileClassify generated by hbm2java
 */
@Entity
@Table(name="catfile_classify"
    ,schema="public"
)
public class CatfileClassify  implements java.io.Serializable {


     private long catid;
     private String catfile;
     private Double airmass;
     private Double magdiff;
     private Double jd;
     private Boolean isRef;
     private Integer gridx;
     private Integer gridy;

    public CatfileClassify() {
    }

	
    public CatfileClassify(long catid) {
        this.catid = catid;
    }
    public CatfileClassify(long catid, String catfile, Double airmass, Double magdiff, Double jd, Boolean isRef, Integer gridx, Integer gridy) {
       this.catid = catid;
       this.catfile = catfile;
       this.airmass = airmass;
       this.magdiff = magdiff;
       this.jd = jd;
       this.isRef = isRef;
       this.gridx = gridx;
       this.gridy = gridy;
    }
   
  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "catfile_classify_catid_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "catid", unique = true, nullable = false)
    public long getCatid() {
        return this.catid;
    }
    
    public void setCatid(long catid) {
        this.catid = catid;
    }

    
    @Column(name="catfile")
    public String getCatfile() {
        return this.catfile;
    }
    
    public void setCatfile(String catfile) {
        this.catfile = catfile;
    }

    
    @Column(name="airmass", precision=17, scale=17)
    public Double getAirmass() {
        return this.airmass;
    }
    
    public void setAirmass(Double airmass) {
        this.airmass = airmass;
    }

    
    @Column(name="magdiff", precision=17, scale=17)
    public Double getMagdiff() {
        return this.magdiff;
    }
    
    public void setMagdiff(Double magdiff) {
        this.magdiff = magdiff;
    }

    
    @Column(name="jd", precision=17, scale=17)
    public Double getJd() {
        return this.jd;
    }
    
    public void setJd(Double jd) {
        this.jd = jd;
    }

    
    @Column(name="is_ref")
    public Boolean getIsRef() {
        return this.isRef;
    }
    
    public void setIsRef(Boolean isRef) {
        this.isRef = isRef;
    }

    
    @Column(name="gridx")
    public Integer getGridx() {
        return this.gridx;
    }
    
    public void setGridx(Integer gridx) {
        this.gridx = gridx;
    }

    
    @Column(name="gridy")
    public Integer getGridy() {
        return this.gridy;
    }
    
    public void setGridy(Integer gridy) {
        this.gridy = gridy;
    }




}


