package com.gwac.model;
// Generated 2016-6-11 16:23:31 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CrossmatchClassify generated by hbm2java
 */
@Entity
@Table(name = "crossmatch_classify", schema = "public"
)
public class CrossmatchClassify implements java.io.Serializable {

  private long cid;
  private Long starid;
  private Long crossid;
  private Double ra;
  private Double dec;
  private Long catid;
  private Double background;
  private Double classstar;
  private Double ellipticity;
  private Double flags;
  private Double mag;
  private Double mage;
  private Double magnorm;
  private Double fwhm;
  private Double magcalib;
  private Double magcalibe;
  private Double pixx;
  private Double pixy;
  private Double thetaimage;
  private Double vignet;
  private Double pixx1;
  private Double pixy1;
  private Double fluxratio;
  private Double jd;

  public CrossmatchClassify() {
  }

  public CrossmatchClassify(long cid) {
    this.cid = cid;
  }

  public CrossmatchClassify(long cid, Long starid, Long crossid, Double ra, Double dec, Long catid, Double background, Double classstar, Double ellipticity, Double flags, Double mag, Double mage, Double magnorm, Double fwhm, Double magcalib, Double magcalibe, Double pixx, Double pixy, Double thetaimage, Double vignet, Double pixx1, Double pixy1, Double fluxratio) {
    this.cid = cid;
    this.starid = starid;
    this.crossid = crossid;
    this.ra = ra;
    this.dec = dec;
    this.catid = catid;
    this.background = background;
    this.classstar = classstar;
    this.ellipticity = ellipticity;
    this.flags = flags;
    this.mag = mag;
    this.mage = mage;
    this.magnorm = magnorm;
    this.fwhm = fwhm;
    this.magcalib = magcalib;
    this.magcalibe = magcalibe;
    this.pixx = pixx;
    this.pixy = pixy;
    this.thetaimage = thetaimage;
    this.vignet = vignet;
    this.pixx1 = pixx1;
    this.pixy1 = pixy1;
    this.fluxratio = fluxratio;
  }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "crossmatch_classify_cid_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "cid", unique = true, nullable = false)
  public long getCid() {
    return this.cid;
  }

  public void setCid(long cid) {
    this.cid = cid;
  }

  @Column(name = "starid")
  public Long getStarid() {
    return this.starid;
  }

  public void setStarid(Long starid) {
    this.starid = starid;
  }

  @Column(name = "crossid")
  public Long getCrossid() {
    return this.crossid;
  }

  public void setCrossid(Long crossid) {
    this.crossid = crossid;
  }

  @Column(name = "ra", precision = 17, scale = 17)
  public Double getRa() {
    return this.ra;
  }

  public void setRa(Double ra) {
    this.ra = ra;
  }

  @Column(name = "dec", precision = 17, scale = 17)
  public Double getDec() {
    return this.dec;
  }

  public void setDec(Double dec) {
    this.dec = dec;
  }

  @Column(name = "catid")
  public Long getCatid() {
    return this.catid;
  }

  public void setCatid(Long catid) {
    this.catid = catid;
  }

  @Column(name = "background", precision = 17, scale = 17)
  public Double getBackground() {
    return this.background;
  }

  public void setBackground(Double background) {
    this.background = background;
  }

  @Column(name = "classstar", precision = 17, scale = 17)
  public Double getClassstar() {
    return this.classstar;
  }

  public void setClassstar(Double classstar) {
    this.classstar = classstar;
  }

  @Column(name = "ellipticity", precision = 17, scale = 17)
  public Double getEllipticity() {
    return this.ellipticity;
  }

  public void setEllipticity(Double ellipticity) {
    this.ellipticity = ellipticity;
  }

  @Column(name = "flags", precision = 17, scale = 17)
  public Double getFlags() {
    return this.flags;
  }

  public void setFlags(Double flags) {
    this.flags = flags;
  }

  @Column(name = "mag", precision = 17, scale = 17)
  public Double getMag() {
    return this.mag;
  }

  public void setMag(Double mag) {
    this.mag = mag;
  }

  @Column(name = "mage", precision = 17, scale = 17)
  public Double getMage() {
    return this.mage;
  }

  public void setMage(Double mage) {
    this.mage = mage;
  }

  @Column(name = "magnorm", precision = 17, scale = 17)
  public Double getMagnorm() {
    return this.magnorm;
  }

  public void setMagnorm(Double magnorm) {
    this.magnorm = magnorm;
  }

  @Column(name = "fwhm", precision = 17, scale = 17)
  public Double getFwhm() {
    return this.fwhm;
  }

  public void setFwhm(Double fwhm) {
    this.fwhm = fwhm;
  }

  @Column(name = "magcalib", precision = 17, scale = 17)
  public Double getMagcalib() {
    return this.magcalib;
  }

  public void setMagcalib(Double magcalib) {
    this.magcalib = magcalib;
  }

  @Column(name = "magcalibe", precision = 17, scale = 17)
  public Double getMagcalibe() {
    return this.magcalibe;
  }

  public void setMagcalibe(Double magcalibe) {
    this.magcalibe = magcalibe;
  }

  @Column(name = "pixx", precision = 17, scale = 17)
  public Double getPixx() {
    return this.pixx;
  }

  public void setPixx(Double pixx) {
    this.pixx = pixx;
  }

  @Column(name = "pixy", precision = 17, scale = 17)
  public Double getPixy() {
    return this.pixy;
  }

  public void setPixy(Double pixy) {
    this.pixy = pixy;
  }

  @Column(name = "thetaimage", precision = 17, scale = 17)
  public Double getThetaimage() {
    return this.thetaimage;
  }

  public void setThetaimage(Double thetaimage) {
    this.thetaimage = thetaimage;
  }

  @Column(name = "vignet", precision = 17, scale = 17)
  public Double getVignet() {
    return this.vignet;
  }

  public void setVignet(Double vignet) {
    this.vignet = vignet;
  }

  @Column(name = "pixx1", precision = 17, scale = 17)
  public Double getPixx1() {
    return this.pixx1;
  }

  public void setPixx1(Double pixx1) {
    this.pixx1 = pixx1;
  }

  @Column(name = "pixy1", precision = 17, scale = 17)
  public Double getPixy1() {
    return this.pixy1;
  }

  public void setPixy1(Double pixy1) {
    this.pixy1 = pixy1;
  }

  @Column(name = "fluxratio", precision = 17, scale = 17)
  public Double getFluxratio() {
    return this.fluxratio;
  }

  public void setFluxratio(Double fluxratio) {
    this.fluxratio = fluxratio;
  }

  /**
   * @return the jd
   */
  @Column(name = "jd", precision = 17, scale = 17)
  public Double getJd() {
    return jd;
  }

  /**
   * @param jd the jd to set
   */
  public void setJd(Double jd) {
    this.jd = jd;
  }

}
