package com.gwac.model;
// Generated 2016-6-11 16:23:31 by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * StarType generated by hbm2java
 */
@Entity
@Table(name = "star_type", schema = "public"
)
public class StarType implements java.io.Serializable {

  private int stId;
  private String stName;
  private String stComment;

  public StarType() {
  }

  public StarType(int stId) {
    this.stId = stId;
  }

  public StarType(int stId, String stName, String stComment) {
    this.stId = stId;
    this.stName = stName;
    this.stComment = stComment;
  }

  @GenericGenerator(name = "generator", strategy = "seqhilo", parameters = {
    @Parameter(name = "max_lo", value = "49"),
    @Parameter(name = "sequence", value = "st_id_seq")})
  @Id
  @GeneratedValue(generator = "generator")
  @Column(name = "st_id", unique = true, nullable = false)
  public int getStId() {
    return this.stId;
  }

  public void setStId(int stId) {
    this.stId = stId;
  }

  @Column(name = "st_name", length = 64)
  public String getStName() {
    return this.stName;
  }

  public void setStName(String stName) {
    this.stName = stName;
  }

  @Column(name = "st_comment", length = 256)
  public String getStComment() {
    return this.stComment;
  }

  public void setStComment(String stComment) {
    this.stComment = stComment;
  }

}
